src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 * fields= {"email"},
 * message= "Adresse email déjà utilisée, merci d'en utiliser une autre."
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Prénom obligatoire")
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Nom de famille obligatoire")
     */
    private $lastname;


    private $fullname;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Email invalide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @Assert\EqualTo(propertyPath="hash", message="Le mot passe et la confirmation de mot passe sont differents")
     */
    private $passwordconfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, minMessage="10 caractères sont requis")
     */
    private $presentation;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url(message="Veuillez donner une Url valide pour votre avatar !")
     */
    private $avatar;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Article::class, mappedBy="author")
     */
    private $articles;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $userRoles;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
    }

    /**
     * Génére un slug automatiquement
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function initSlug(){
        if(empty($this->slug) ){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->getFullname().time().hash("sha1", $this->getFirstname()) );
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFullname(): ?string
    {
        return $this->lastname . " " . $this->firstname;
    }

    public function setFullname(string $fullname): self
    {
        $this->fullname = $fullname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getPasswordconfirm(): ?string
    {
        return $this->passwordconfirm;
    }

    public function setPasswordconfirm(string $passwordconfirm): self
    {
        $this->passwordconfirm = $passwordconfirm;

        return $this;
    }

    public function getPresentation(): ?string
    {
        return $this->presentation;
    }

    public function setPresentation(string $presentation): self
    {
        $this->presentation = $presentation;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getAvatar()
    {
        return $this->avatar;
    }

    public function setAvatar($avatar)
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): self
    {
        if (!$this->articles->contains($article)) {
            $this->articles[] = $article;
            $article->setAuthor($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): self
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getAuthor() === $this) {
                $article->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles() {
        return ['ROLE_USER'];
    }

    public function getPassword() {
        return $this->hash;
    }

    public function getSalt() {
        return null;
    }

    public function eraseCredentials() {

    }

    public function getUsername() {
        return (string) $this->email;
    }

    public function getUserIdentifier() {
        return (string) $this->email;
    }

    /**
     * @return Collection<int, Role>
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->removeElement($userRole)) {
            $userRole->removeUser($this);
        }

        return $this;
    }
}

templates/partials/card.article.html.twig
<div class="col-xl-4 col-lg-4 col-md-8 col-sm-10 m-auto text-center">

    <div class="card bg-light mb-5 shadow">

        <h3 class="card-header">{{article.title | title}}</h3>   
        <img height="350px" class="rounded-circle border border-success m-2" src="{{article.image}}" alt="Card image">
        
        <div class="card-body">
          <p class="card-text">{{article.intro | capitalize}}</p>
          <a href="{{ path('article_show', {'slug':article.slug}) }}" class="btn btn-primary rounded">Lire la suite</a>

          <div class="my-3">
              <a href="{{ path('account_profil', {'slug':article.author.slug}) }}" class="card-link">
                {{article.author.fullname}}
              </a>
          </div>
          
        </div>
        <div class="card-footer text-muted">
          {{ article.createdAt | date("d/m/Y à H:i") }}
        </div>
    </div>
</div>

 

templates/partials/footer.html.twig
<footer class=" text-center p-3 bg-primary text-white">
    <div class="container p-4">
        <h3>Nos réseaux sociaux</h3>
        <hr>
        <a class='btn m-1 text-white' href="https://facebook.com"><i class="fab fa-facebook-f fa-lg"></i></a>
        <a class='btn m-1 text-white' href="https://linkedin.com"><i class="fab fa-linkedin-in fa-lg"></i></a>
        <a class='btn m-1 text-white' href="https://github.com"><i class="fab fa-github fa-lg"></i></a>
    </div>

    <p>Copyright YesCode - {{ "now"|date("Y") }} </p>
</footer>

templates/partials/header.html.twig
<header>
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
		<a class="navbar-brand" href="{{path("home_page")}}">YesCode</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarColor01">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<a class="nav-link" href="{{path("home_page")}}">
						<i class="fa fa-home"></i>
						Accueil
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{path("articles_index")}}">
						<i class="fa fa-newspaper"></i>
						Articles
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{path("users_list")}}">
						<i class="fa fa-user"></i>						
						Utilisateurs
					</a>
				</li>
				{% if app.user %}
					<li class="nav-item">
						<a class="nav-link" href="{{path("article_create")}}">
							<i class="fa fa-pen"></i>
							Ecrire un article
						</a>
					</li>
				{% endif %}
			</ul>
						
			<ul class="navbar-nav ml-auto">

			{% if app.user %}
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
						<i class="fa fa-user"></i>
						{{app.user.fullname | title }}
					</a>
					<div class="dropdown-menu dropdown-menu-right">
						<a class="dropdown-item" href="{{ path('account_profil', {'slug': app.user.slug } )}}">Mon Profil</a>
						<a class="dropdown-item" href="{{ path('article_create')}}">Ecrire un article</a>
						<a class="dropdown-item" href="#">Mes articles</a>

						{% if app.user.roles == 'admin' %}
							<a class="dropdown-item" href="{{ path('users_list')}}">Espace Admin</a>
						{% endif %}

						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{{ path('account_logout')}}">Déconnexion</a>
					</div>
				</li>
			{% else %}
				<li class="nav-item mx-3">
					<a class="nav-link"  href="{{ path('account_create') }}" role="button" aria-haspopup="true" aria-expanded="false">
						<i class="fa fa-user-plus"></i>
						Inscription
					</a>
				</li>
				<li class="nav-item mx-3">
					<a class="nav-link"  href="{{ path('account_login') }}" role="button" aria-haspopup="true" aria-expanded="false">
						<i class="fas fa-sign-in-alt"></i>
						Connexion
					</a>
				</li>		
			{% endif %}
			
			</ul>
		</div>
	</nav>
</header>

{# message en desous du header lorsqu'on publie un article #}
{% for label, messages in app.flashes %}
	<div class="container text-center my-5">
		<div class="alert alert-{{ label }}">
			{% for message in messages %}
				<p>{{ message | raw }}</p>
			{% endfor %}
		</div>
	</div>
{% endfor %}

templates/partials/scripts.html.twig
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>